import { Droplets, Wheat, Leaf, Apple, Beef, Coffee } from "lucide-react"

export const categories = [
  {
    id: 1,
    name: "السمن والزبدة",
    slug: "ghee",
    icon: Droplets,
  },
  {
    id: 2,
    name: "العسل الطبيعي",
    slug: "honey",
    icon: Wheat,
  },
  {
    id: 3,
    name: "زيت الزيتون",
    slug: "olive-oil",
    icon: Leaf,
  },
  {
    id: 4,
    name: "الأجبان",
    slug: "cheese",
    icon: Apple,
  },
  {
    id: 5,
    name: "المكسرات",
    slug: "nuts",
    icon: Coffee,
  },
  {
    id: 6,
    name: "اللحوم المجففة",
    slug: "dried-meat",
    icon: Beef,
  },
]

export const products = [
  {
    id: 1,
    name: "سمن بلدي حلبي",
    description: "سمن بلدي طبيعي 100% من أجود أنواع الحليب البقري",
    price: "25.00 $",
    originalPrice: "30.00 $",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    isNew: false,
    isBestSeller: true,
    discount: 17,
    categoryId: 1,
  },
  {
    id: 2,
    name: "عسل جبلي طبيعي",
    description: "عسل جبلي من مناحل الجبال السورية الطبيعية",
    price: "30.00 $",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    isNew: true,
    isBestSeller: false,
    categoryId: 2,
  },
  {
    id: 3,
    name: "زيت زيتون بكر ممتاز",
    description: "زيت زيتون بكر ممتاز معصور على البارد من أشجار معمرة",
    price: "20.00 $",
    originalPrice: "24.00 $",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    isNew: false,
    isBestSeller: false,
    discount: 17,
    categoryId: 3,
  },
  {
    id: 4,
    name: "جبنة حلوم سورية",
    description: "جبنة حلوم سورية تقليدية مصنوعة يدوياً",
    price: "15.00 $",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    isNew: false,
    isBestSeller: false,
    categoryId: 4,
  },
  {
    id: 5,
    name: "فستق حلبي",
    description: "فستق حلبي محمص طازج من أجود أنواع الفستق السوري",
    price: "35.00 $",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    isNew: false,
    isBestSeller: true,
    categoryId: 5,
  },
  {
    id: 6,
    name: "عسل السدر",
    description: "عسل سدر أصلي من أفضل مناحل الجزيرة العربية",
    price: "40.00 $",
    image: "/placeholder.svg?height=400&width=400",
    rating: 5.0,
    isNew: true,
    isBestSeller: false,
    categoryId: 2,
  },
  {
    id: 7,
    name: "زيت زيتون عضوي",
    description: "زيت زيتون عضوي معتمد من مزارع خالية من المبيدات",
    price: "28.00 $",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    isNew: true,
    isBestSeller: false,
    categoryId: 3,
  },
  {
    id: 8,
    name: "جبنة بيضاء بلدية",
    description: "جبنة بيضاء بلدية طازجة مصنوعة من حليب الأغنام",
    price: "12.00 $",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    isNew: false,
    isBestSeller: false,
    categoryId: 4,
  },
]

export const testimonials = [
  {
    name: "أحمد محمود",
    location: "دمشق، سوريا",
    text: "منتجات ذواقة المشرق تعيدني إلى ذكريات الطفولة في حلب. السمن البلدي لديهم هو الأفضل على الإطلاق! أوصي به بشدة لكل من يبحث عن الطعم الأصيل.",
    avatar: "/placeholder.svg?height=100&width=100",
    rating: 5,
  },
  {
    name: "سارة خالد",
    location: "بيروت، لبنان",
    text: "أنا أطلب منتجاتهم بانتظام. زيت الزيتون لديهم له نكهة فريدة لا مثيل لها في السوق. الجودة ممتازة والتوصيل سريع ومضمون.",
    avatar: "/placeholder.svg?height=100&width=100",
    rating: 4,
  },
  {
    name: "محمد عبدالله",
    location: "عمان، الأردن",
    text: "العسل الجبلي من ذواقة المشرق هو الأصدق والأنقى. أوصي به بشدة لكل محبي العسل الطبيعي. لقد أصبح جزءًا أساسيًا من فطوري اليومي.",
    avatar: "/placeholder.svg?height=100&width=100",
    rating: 5,
  },
]
